version: "3.8"

services:
  messenger1:
    build: .
    container_name: messenger1
    networks:
      - p2p_network
    ports:
      - "1235:1235"
    environment:
      - USER_ID=Adam
      - PORT=1235
    volumes:
      - ./src/.config:/app/.config

  messenger2:
    build: .
    container_name: messenger2
    networks:
      - p2p_network
    ports:
      - "1236:1236"
    environment:
      - USER_ID=Eve
      - PORT=1236
    volumes:
      - ./src/.config:/app/.config

  messenger3:
    build: .
    container_name: messenger3
    networks:
      - p2p_network
    ports:
      - "1237:1237"
    environment:
      - USER_ID=Bob
      - PORT=1237
    volumes:
      - ./src/.config:/app/.config

networks:
  p2p_network:
    driver: bridge
