version: "3.8"

services:
  messenger1:
    build: .
    container_name: messenger1
    stdin_open: true
    tty: true
    networks:
      p2p_network:
        ipv4_address: 172.18.0.2
    ports:
      - "1235:1235"
    environment:
      - USER_ID=Adam
      - PORT=1235
    volumes:
      - ./src/.config:/app/.config

  messenger2:
    build: .
    container_name: messenger2
    stdin_open: true
    tty: true
    networks:
      p2p_network:
        ipv4_address: 172.18.0.3
    ports:
      - "1236:1236"
    environment:
      - USER_ID=Eve
      - PORT=1236
    volumes:
      - ./src/.config:/app/.config

  messenger3:
    build: .
    container_name: messenger3
    stdin_open: true
    tty: true
    networks:
      p2p_network:
        ipv4_address: 172.18.0.4
    ports:
      - "1237:1237"
    environment:
      - USER_ID=Bob
      - PORT=1237
    volumes:
      - ./src/.config:/app/.config

networks:
  p2p_network:
    name: p2p_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
