# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.8"

services:
  messenger1:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - USER_ID=Adam
      - PORT=1235
    networks:
      messenger_net:
        ipv4_address: 172.20.0.2

  messenger2:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - USER_ID=Eve
      - PORT=1236
    networks:
      messenger_net:
        ipv4_address: 172.20.0.3

  messenger3:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - USER_ID=Bob
      - PORT=1237
    networks:
      messenger_net:
        ipv4_address: 172.20.0.4

networks:
  messenger_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
